# Generated by Django 5.1.3 on 2024-11-23 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение в центре')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст в центре')),
            ],
            options={
                'verbose_name': 'контент по центру про нас',
                'verbose_name_plural': 'Контент по центру про нас',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение в центре')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст в центре')),
            ],
            options={
                'verbose_name': 'контент по центру контакты',
                'verbose_name_plural': 'Контент по центру контакты',
            },
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение в центре')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст в центре')),
            ],
            options={
                'verbose_name': 'контент по центру главная',
                'verbose_name_plural': 'Контент по центру главная',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение в центре')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст в центре')),
            ],
            options={
                'verbose_name': 'контент по центру меню',
                'verbose_name_plural': 'Контент по центру меню',
            },
        ),
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение справа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст справа')),
            ],
            options={
                'verbose_name': 'контент справа главная',
                'verbose_name_plural': 'Контент справа главная',
            },
        ),
        migrations.CreateModel(
            name='Rightab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение справа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст справа')),
            ],
            options={
                'verbose_name': 'контент справа про нас',
                'verbose_name_plural': 'Контент справа про нас',
            },
        ),
        migrations.CreateModel(
            name='Rightcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение справа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст справа')),
            ],
            options={
                'verbose_name': 'контент справа контакты',
                'verbose_name_plural': 'Контент справа контакты',
            },
        ),
        migrations.CreateModel(
            name='Rightmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('image', models.ImageField(blank=True, null=True, upload_to='carusel_images', verbose_name='Изображение справа')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст справа')),
            ],
            options={
                'verbose_name': 'контент справа меню',
                'verbose_name_plural': 'Контент справа меню',
            },
        ),
    ]
