# Generated by Django 5.1.3 on 2024-11-24 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'про нас центр', 'verbose_name_plural': 'Про нас центр'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'контакты центр', 'verbose_name_plural': 'Контакты центр'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'главная центр', 'verbose_name_plural': 'Главная центр'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню центр', 'verbose_name_plural': 'меню центр'},
        ),
        migrations.AlterModelOptions(
            name='right',
            options={'verbose_name': 'главная справа', 'verbose_name_plural': 'Главная справа'},
        ),
        migrations.AlterModelOptions(
            name='rightab',
            options={'verbose_name': 'про нас справа', 'verbose_name_plural': 'Про нас справа'},
        ),
        migrations.AlterModelOptions(
            name='rightcon',
            options={'verbose_name': 'контакты справа', 'verbose_name_plural': 'Контакты справа'},
        ),
        migrations.AlterModelOptions(
            name='rightmen',
            options={'verbose_name': 'меню справа', 'verbose_name_plural': 'меню справа'},
        ),
    ]
