# Generated by Django 5.1 on 2024-09-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name': 'Доставку', 'verbose_name_plural': 'Доставка'},
        ),
        migrations.AlterField(
            model_name='about',
            name='article',
            field=models.TextField(verbose_name='Информация:'),
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.CharField(max_length=50, verbose_name='Тема:'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=250, verbose_name='Адрес:'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='E-mail:'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон:'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='article',
            field=models.TextField(verbose_name='Информация:'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='content',
            field=models.CharField(max_length=50, verbose_name='Тема:'),
        ),
    ]
